/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface XTooltip {
    'text': string;
  }
}

declare global {


  interface HTMLXTooltipElement extends Components.XTooltip, HTMLStencilElement {}
  var HTMLXTooltipElement: {
    prototype: HTMLXTooltipElement;
    new (): HTMLXTooltipElement;
  };
  interface HTMLElementTagNameMap {
    'x-tooltip': HTMLXTooltipElement;
  }
}

declare namespace LocalJSX {
  interface XTooltip {
    'text'?: string;
  }

  interface IntrinsicElements {
    'x-tooltip': XTooltip;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'x-tooltip': LocalJSX.XTooltip & JSXBase.HTMLAttributes<HTMLXTooltipElement>;
    }
  }
}


